ex_nihilo_guild:
    resource: "@ExNihiloGuildBundle/Resources/config/routing.yml"
    prefix:   /

ex_nihilo_event:
    resource: "@ExNihiloEventBundle/Resources/config/routing.yml"
    prefix:   /

ex_nihilo_platform:
    resource: "@ExNihiloPlatformBundle/Resources/config/routing.yml"
    prefix:   /

ex_nihilo_user:
    resource: "@ExNihiloUserBundle/Resources/config/routing.yml"

ex_nihilo_blog:
    resource: "@ExNihiloBlogBundle/Resources/config/routing.yml"

