admin_article_index:
    path:     /
    defaults: { _controller: "ExNihiloBlogBundle:Article:index" }
    methods:  GET

admin_article_show:
    path:     /{id}/show
    defaults: { _controller: "ExNihiloBlogBundle:Article:show" }
    methods:  GET

admin_article_new:
    path:     /new
    defaults: { _controller: "ExNihiloBlogBundle:Article:new" }
    methods:  [GET, POST]

admin_article_edit:
    path:     /{id}/edit
    defaults: { _controller: "ExNihiloBlogBundle:Article:edit" }
    methods:  [GET, POST]

admin_article_delete:
    path:     /{id}/delete
    defaults: { _controller: "ExNihiloBlogBundle:Article:delete" }
    methods:  DELETE
