admin_comment_index:
    path:     /
    defaults: { _controller: "ExNihiloBlogBundle:Comment:index" }
    methods:  GET

admin_comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "ExNihiloBlogBundle:Comment:edit" }
    methods:  [GET, POST]

admin_comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "ExNihiloBlogBundle:Comment:delete" }
    methods:  GET

admin_comment_new:
    path:     /new/{articleId}
    defaults: { _controller: "ExNihiloBlogBundle:Comment:new" }
    methods:  [GET, POST]