admin_user_index:
    path:     /
    defaults: { _controller: "ExNihiloUserBundle:User:index" }
    methods:  GET

admin_user_new:
    path:     /new
    defaults: { _controller: "ExNihiloUserBundle:User:new" }
    methods:  [GET, POST]

admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "ExNihiloUserBundle:User:edit" }
    methods:  [GET, POST]

admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "ExNihiloUserBundle:User:delete" }
    methods:  [GET, DELETE]
